package com.github.slmpc.prismrhi.backend;

public enum BackendFeature {
    COMPATIBILITY_PROFILE,
    DIRECT_STATE_ACCESS,
    EXPLICIT_MEMORY,
    EXPLICIT_SYNCHRONIZATION,
    SPIRV_SHADER_MODULES,
    GLSL_SHADER_MODULES,
    COMMAND_BUFFERS,
    DESCRIPTORS,
    DESCRIPTOR_INDEXING,
    GRAPHICS_PIPELINES,
    DYNAMIC_RENDERING,
    FRAME_GRAPH,
    MULTI_DRAW,
    DEBUG_LABELS
}
